// Generated by CoffeeScript 1.6.3
(function() {
  var Account, Users, users,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Account = (function() {
    function Account() {
      this.sayHello = 'hi';
    }

    Account.prototype.getInfo = function() {
      return {
        company: 'Human Design',
        companyAddress: '1035 Pearl St. #207 Boulder, CO 80302'
      };
    };

    return Account;

  })();

  Users = (function(_super) {
    __extends(Users, _super);

    function Users() {
      console.log(this);
      this.getInfo();
    }

    Users.prototype.getInfo = function() {
      this.userInfo = Users.__super__.getInfo.call(this);
      this.userInfo.name = "Matt";
      this.userInfo.age = 72;
      return console.log(this.userInfo);
    };

    return Users;

  })(Account);

  users = new Users();

  console.log('hi');

}).call(this);
